name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - flake8
  - pytest
  - aiohttp
  - transformers
  - pyyaml
  - vaderSentiment=3.3.2
  - nltk
  - pymc
  - sympy
  - arviz
